Repository vinteumorg/Floresta, pull requests merged in 2024-12, with the labels that each got.

#313 Fix all typos
  crates/floresta-chain/src/pruned_utreexo/chainparams.rs
  crates/floresta-chain/src/pruned_utreexo/mod.rs
  crates/floresta-chain/src/pruned_utreexo/partial_chain.rs
  crates/floresta-cli/src/rpc.rs
  crates/floresta-cli/src/rpc_types.rs
  crates/floresta-common/src/spsc.rs
  crates/floresta-compact-filters/src/flat_filters_store.rs
  crates/floresta-compact-filters/src/lib.rs
  crates/floresta-compact-filters/src/network_filters.rs
  crates/floresta-electrum/src/electrum_protocol.rs
  crates/floresta-watch-only/src/lib.rs
  crates/floresta-wire/src/cli_wire/mod.rs
  crates/floresta-wire/src/p2p_wire/chain_selector.rs
  crates/floresta-wire/src/p2p_wire/error.rs
  crates/floresta-wire/src/p2p_wire/node_context.rs
  crates/floresta-wire/src/p2p_wire/running_node.rs
  crates/floresta-wire/src/p2p_wire/sync_node.rs
  crates/floresta-wire/src/p2p_wire/tests/test_data/block_hashes.txt
  crates/floresta/src/lib.rs
  florestad/docs/tutorial(PT-BR).md
  florestad/src/cli.rs
  florestad/src/florestad.rs
  florestad/src/json_rpc/server.rs
  florestad/src/zmq.rs
  tests/example_test.py
  tests/prepare.sh
Labels: documentation, code quality

#314 Add prometheus support
  Cargo.lock
  Cargo.toml
  Dockerfile
  README.md
  crates/floresta-chain/Cargo.toml
  crates/floresta-chain/src/pruned_utreexo/chain_state.rs
  docker-compose.yml
  florestad/Cargo.toml
  florestad/src/florestad.rs
  metrics/Cargo.toml
  metrics/grafana/datasource.yml
  metrics/prometheus/prometheus.yml
  metrics/src/lib.rs
Labels: enhancement

#309 Structure improvement functional tests
  .github/workflows/functional.yml
  README.md
  poetry.lock
  pyproject.toml
  tests/example_test.py
  tests/restart.py
  tests/run_tests.py
  tests/test_framework/bitcoin.py
  tests/test_framework/crypto/secp256k1.py
  tests/test_framework/electrum_client.py
  tests/test_framework/floresta_rpc.py
  tests/test_framework/key.py
  tests/test_framework/mock_rpc.py
  tests/test_framework/test_framework.py
  tests/test_framework/utreexod.py
Labels: dependencies, code quality, functional tests

#322 json-rpc: use axum for server
  Cargo.lock
  florestad/Cargo.toml
  florestad/src/florestad.rs
  florestad/src/json_rpc/res.rs
  florestad/src/json_rpc/server.rs
  tests/test_framework/floresta_rpc.py
Labels: dependencies, code quality
