Repository vinteumorg/Floresta, pull requests merged in 2025-03, with the labels that each got.

#401 added docs to prunned_utreexo module and its submodules
  crates/floresta-chain/src/lib.rs
  crates/floresta-chain/src/pruned_utreexo/chain_state.rs
  crates/floresta-chain/src/pruned_utreexo/chain_state_builder.rs
  crates/floresta-chain/src/pruned_utreexo/chainparams.rs
  crates/floresta-chain/src/pruned_utreexo/error.rs
  crates/floresta-chain/src/pruned_utreexo/mod.rs
Labels: documentation, chore, code quality

#402 Re-structured functional tests.
  .github/workflows/functional.yml
  .gitignore
  README.md
  poetry.lock
  pyproject.toml
  tests/__init__.py
  tests/example/example-test.py
  tests/floresta-cli/addnode-test.py
  tests/floresta-cli/getblock-test.py
  tests/floresta-cli/getblockchaininfo-test.py
  tests/floresta-cli/getblockhash-test.py
  tests/floresta-cli/getblockheader-test.py
  tests/floresta-cli/getmemoryinfo-test.py
  tests/floresta-cli/getpeerinfo-test.py
  tests/floresta-cli/getroots-test.py
  tests/floresta-cli/getrpcinfo-test.py
  tests/floresta-cli/stop-test.py
  tests/floresta-cli/uptime-test.py
  tests/florestad/restart-test.py
  tests/prepare.sh
  tests/requirements.txt
  tests/run.sh
  tests/run_tests.py
  tests/test_framework/__init__.py
  tests/test_framework/bitcoin.py
  tests/test_framework/floresta_rpc.py
  tests/test_framework/key.py
  uv.lock
Labels: dependencies, code quality, functional tests

#414 Validate utreexo node hashes at compile time
  crates/floresta-chain/src/lib.rs
  crates/floresta-chain/src/pruned_utreexo/chain_state.rs
  crates/floresta-chain/src/pruned_utreexo/chainparams.rs
  crates/floresta-chain/src/pruned_utreexo/partial_chain.rs
  crates/floresta-chain/src/pruned_utreexo/udata.rs
  crates/floresta-common/src/lib.rs
  crates/floresta-common/src/macros.rs
  crates/floresta-wire/src/p2p_wire/mempool.rs
  crates/floresta-wire/src/p2p_wire/tests/utils.rs
Labels: code quality
