Repository vinteumorg/Floresta, pull requests merged in 2025-05, with the labels that each got.

#471 Handle ChainStateBuilder errors, avoid unwraps
  crates/floresta-chain/src/pruned_utreexo/chain_state.rs
  crates/floresta-chain/src/pruned_utreexo/chain_state_builder.rs
  crates/floresta-chain/src/pruned_utreexo/error.rs
  crates/floresta/examples/chainstate-builder.rs
Labels: enhancement, code quality

#475 Small refactors to remove unwraps
  crates/floresta-chain/src/pruned_utreexo/chainstore.rs
  crates/floresta-chain/src/pruned_utreexo/partial_chain.rs
  crates/floresta-chain/src/pruned_utreexo/udata.rs
Labels: documentation, chore, code quality

#467 [FIX] prepare.sh now override pre-built binaires
  .github/workflows/functional.yml
  doc/running-tests.md
  tests/prepare.sh
Labels: bug, functional tests

#473 chore: use `bitcoin::Network` instead of wrapper enum
  crates/floresta-chain/benches/chain_state_bench.rs
  crates/floresta-chain/src/lib.rs
  crates/floresta-chain/src/pruned_utreexo/chain_state.rs
  crates/floresta-chain/src/pruned_utreexo/chain_state_builder.rs
  crates/floresta-chain/src/pruned_utreexo/chainparams.rs
  crates/floresta-chain/src/pruned_utreexo/error.rs
  crates/floresta-chain/src/pruned_utreexo/partial_chain.rs
  crates/floresta-chain/src/pruned_utreexo/udata.rs
  crates/floresta-electrum/src/electrum_protocol.rs
  crates/floresta-wire/src/p2p_wire/address_man.rs
  crates/floresta-wire/src/p2p_wire/node.rs
  crates/floresta-wire/src/p2p_wire/tests/sync_node.rs
  crates/floresta-wire/src/p2p_wire/tests/utils.rs
  crates/floresta/examples/chainstate-builder.rs
  crates/floresta/examples/node.rs
  florestad/src/cli.rs
  florestad/src/florestad.rs
  florestad/src/lib.rs
  florestad/src/main.rs
  florestad/src/wallet_input.rs
Labels: dependencies, chore, code quality

#476 Debug test data with `assert_ok` and `assert_err`
  crates/floresta-chain/src/pruned_utreexo/chain_state.rs
  crates/floresta-chain/src/pruned_utreexo/consensus.rs
  crates/floresta-common/src/macros.rs
  crates/floresta-electrum/src/electrum_protocol.rs
  crates/floresta-watch-only/src/merkle.rs
  crates/floresta-wire/src/p2p_wire/address_man.rs
  crates/floresta-wire/src/p2p_wire/mempool.rs
Labels: chore, code quality

#478 Deny unwraps in `floresta-chain`, handle errors
  crates/floresta-chain/src/lib.rs
  crates/floresta-chain/src/pruned_utreexo/chain_state.rs
  crates/floresta-chain/src/pruned_utreexo/chainstore.rs
  crates/floresta-chain/src/pruned_utreexo/error.rs
Labels: code quality

#477 [Fix] Fix doc warnings
  crates/floresta-chain/src/pruned_utreexo/consensus.rs
  crates/floresta-chain/src/pruned_utreexo/mod.rs
  crates/floresta-compact-filters/src/lib.rs
  crates/floresta-electrum/src/electrum_protocol.rs
  florestad/src/florestad.rs
  rust-toolchain.toml
Labels: documentation, chore, code quality

#481 feat: add BIP30 check
  crates/floresta-chain/src/pruned_utreexo/consensus.rs
  crates/floresta-chain/src/pruned_utreexo/error.rs
  crates/floresta-wire/src/p2p_wire/running_node.rs
  crates/floresta-wire/src/p2p_wire/sync_node.rs
Labels: consensus

#482 [Fix] Created `just open-doc` command
  justfile
Labels: bug, documentation

#485 Update the `log` crate
  Cargo.lock
  crates/floresta-chain/src/pruned_utreexo/consensus.rs
  crates/floresta-electrum/src/electrum_protocol.rs
  crates/floresta-watch-only/src/lib.rs
  crates/floresta-wire/src/p2p_wire/chain_selector.rs
  crates/floresta-wire/src/p2p_wire/node.rs
  crates/floresta-wire/src/p2p_wire/peer.rs
  crates/floresta-wire/src/p2p_wire/running_node.rs
  crates/floresta-wire/src/p2p_wire/sync_node.rs
  crates/floresta-wire/src/p2p_wire/transport.rs
  florestad/src/florestad.rs
  florestad/src/json_rpc/server.rs
Labels: dependencies, chore

#489 Fix clippy warning for load_descriptor in florestad json_rpc server
  florestad/src/json_rpc/server.rs
Labels: lint

#484 Added missing docs to Floresta Common
  crates/floresta-common/src/lib.rs
  crates/floresta-common/src/macros.rs
Labels: documentation, enhancement, code quality

#483 chore: update tokio-rustls to the latest version
  Cargo.lock
  crates/floresta-electrum/Cargo.toml
  crates/floresta-electrum/src/electrum_protocol.rs
  florestad/Cargo.toml
  florestad/src/error.rs
  florestad/src/florestad.rs
  pyproject.toml
  tests/example/electrum-test.py
  tests/florestad/ssl-test.py
  tests/test_framework/electrum/base.py
  uv.lock
Labels: dependencies, chore, functional tests

#491 fuzz: add target for addrman
  doc/fuzzing.md
  fuzz/Cargo.toml
  fuzz/fuzz_targets/addrman.rs
Labels: code quality, fuzz

#492 Use fresh chainstates for each bencher iteration
  crates/floresta-chain/benches/chain_state_bench.rs
Labels: bug

#375 [Fix] Import sync_node and chain_selector
  crates/floresta-wire/src/lib.rs
  crates/floresta-wire/src/p2p_wire/node.rs
  crates/floresta-wire/src/p2p_wire/node_interface.rs
  crates/floresta-wire/src/p2p_wire/running_node.rs
Labels: documentation, code quality

#493 Optimize `FlatChainStore` and improve tests
  crates/floresta-chain/src/pruned_utreexo/chainstore.rs
  crates/floresta-chain/src/pruned_utreexo/flat_chain_store.rs
Labels: code quality, performance

#472 [Rpcsaga] add blockhash to gettxoutproof
  crates/floresta-cli/src/lib.rs
  crates/floresta-cli/src/main.rs
  crates/floresta-cli/src/parsers.rs
  crates/floresta-cli/src/rpc.rs
  crates/floresta-cli/src/rpc_types.rs
  crates/floresta-electrum/src/electrum_protocol.rs
  crates/floresta-watch-only/src/lib.rs
  crates/floresta-watch-only/src/merkle.rs
  crates/floresta-wire/src/p2p_wire/node.rs
  florestad/Cargo.toml
  florestad/src/json_rpc/blockchain.rs
  florestad/src/json_rpc/res.rs
  florestad/src/json_rpc/server.rs
Labels: bug, RPC

#488 Bugfix: fix two bugs that may happen after an unclean shutdown
  crates/floresta-chain/src/pruned_utreexo/chain_state.rs
  crates/floresta-chain/src/pruned_utreexo/error.rs
  crates/floresta-wire/src/p2p_wire/running_node.rs
  crates/floresta-wire/src/p2p_wire/sync_node.rs
Labels: bug

#479 flat-chain-store: Detect file corruption and reindex if needed.
  Cargo.lock
  crates/floresta-chain/Cargo.toml
  crates/floresta-chain/src/pruned_utreexo/chain_state.rs
  crates/floresta-chain/src/pruned_utreexo/chainstore.rs
  crates/floresta-chain/src/pruned_utreexo/flat_chain_store.rs
  crates/floresta-chain/src/pruned_utreexo/mod.rs
  florestad/src/florestad.rs
Labels: enhancement

#495 Group chain traits
  crates/floresta-chain/src/lib.rs
  crates/floresta-chain/src/pruned_utreexo/mod.rs
  crates/floresta-wire/src/p2p_wire/chain_selector.rs
  crates/floresta-wire/src/p2p_wire/node.rs
  crates/floresta-wire/src/p2p_wire/running_node.rs
  crates/floresta-wire/src/p2p_wire/sync_node.rs
  florestad/src/json_rpc/server.rs
Labels: code quality
