Repository vinteumorg/Floresta, pull requests merged in 2025-04, with the labels that each got.

#412 wire: refactor the handle to use notifications
  crates/floresta-electrum/src/electrum_protocol.rs
  crates/floresta-wire/src/p2p_wire/chain_selector.rs
  crates/floresta-wire/src/p2p_wire/error.rs
  crates/floresta-wire/src/p2p_wire/node.rs
  crates/floresta-wire/src/p2p_wire/node_interface.rs
  crates/floresta-wire/src/p2p_wire/running_node.rs
  crates/floresta-wire/src/p2p_wire/sync_node.rs
  crates/floresta/examples/node.rs
  florestad/src/json_rpc/blockchain.rs
  florestad/src/json_rpc/res.rs
  florestad/src/json_rpc/server.rs
Labels: chore, code quality, performance

#442 running_node: don't ask for blocks until utreexo peers announce it
  crates/floresta-wire/src/p2p_wire/running_node.rs
  crates/floresta-wire/src/p2p_wire/sync_node.rs
Labels: bug, code quality

#444 Add `testdata` utxo files with `UtxoData`
  .github/workflows/benchmarks.yml
  crates/floresta-chain/Cargo.toml
  crates/floresta-chain/benches/chain_state_bench.rs
  crates/floresta-chain/src/pruned_utreexo/chain_state.rs
  crates/floresta-chain/src/pruned_utreexo/mod.rs
  crates/floresta-chain/testdata/block_367891/spent_txos.zst
  crates/floresta-chain/testdata/block_367891/spent_utxos.zst
  crates/floresta-chain/testdata/block_866342/spent_txos.zst
  crates/floresta-chain/testdata/block_866342/spent_utxos.zst
  doc/benchmarking.md
  justfile
Labels: enhancement, chore, code quality

#455 functional-tests: allow using different versions of utreexod
  doc/running-tests.md
  tests/floresta-cli/addnode-test.py
  tests/floresta-cli/getmemoryinfo-test.py
  tests/floresta-cli/getrpcinfo-test.py
  tests/floresta-cli/uptime-test.py
  tests/florestad/restart-test.py
  tests/prepare.sh
  tests/run.sh
  tests/run_tests.py
  tests/test_framework/test_framework.py
Labels: bug, functional tests

#447 Added simple docs to structs and enums of error
  crates/floresta-chain/src/pruned_utreexo/error.rs
Labels: documentation, chore

#446 Added docs for chain store module
  crates/floresta-chain/src/pruned_utreexo/chainstore.rs
Labels: documentation, chore

#459 Fix rust lint warnings
  crates/floresta-chain/src/pruned_utreexo/chain_state.rs
  crates/floresta-chain/src/pruned_utreexo/consensus.rs
  crates/floresta-chain/src/pruned_utreexo/error.rs
  crates/floresta-cli/src/lib.rs
  crates/floresta-cli/src/main.rs
  crates/floresta-compact-filters/src/flat_filters_store.rs
  crates/floresta-electrum/src/electrum_protocol.rs
  crates/floresta-watch-only/src/kv_database.rs
  crates/floresta-watch-only/src/lib.rs
  crates/floresta-wire/src/p2p_wire/address_man.rs
  crates/floresta-wire/src/p2p_wire/node.rs
  crates/floresta/examples/node.rs
  crates/floresta/examples/watch-only.rs
  florestad/build.rs
  florestad/src/error.rs
  florestad/src/florestad.rs
  florestad/src/json_rpc/res.rs
Labels: chore, lint, CI

#452 Generalizing test_framework to allow utreexod in integration tests
  tests/example/electrum-test.py
  tests/example/example-test.py
  tests/example/functional-test.py
  tests/example/integration-test.py
  tests/example/utreexo-test.py
  tests/floresta-cli/addnode-test.py
  tests/floresta-cli/getblock-test.py
  tests/floresta-cli/getblockchaininfo-test.py
  tests/floresta-cli/getblockhash-test.py
  tests/floresta-cli/getblockheader-test.py
  tests/floresta-cli/getmemoryinfo-test.py
  tests/floresta-cli/getpeerinfo-test.py
  tests/floresta-cli/getroots-test.py
  tests/floresta-cli/getrpcinfo-test.py
  tests/floresta-cli/stop-test.py
  tests/floresta-cli/uptime-test.py
  tests/florestad/restart-test.py
  tests/florestad/ssl-fail-test.py
  tests/florestad/ssl-test.py
  tests/run_tests.py
  tests/test_framework/__init__.py
  tests/test_framework/daemon/__init__.py
  tests/test_framework/daemon/base.py
  tests/test_framework/daemon/floresta.py
  tests/test_framework/daemon/utreexo.py
  tests/test_framework/electrum/__init__.py
  tests/test_framework/electrum/base.py
  tests/test_framework/electrum/client.py
  tests/test_framework/floresta_rpc.py
  tests/test_framework/rpc/__init__.py
  tests/test_framework/rpc/base.py
  tests/test_framework/rpc/exceptions.py
  tests/test_framework/rpc/floresta.py
  tests/test_framework/rpc/utreexo.py
  tests/test_framework/test_framework.py
  tests/test_framework/utreexod.py
Labels: enhancement, chore, code quality, functional tests

#464 chain: fix a CI break with linting
  crates/floresta-chain/src/pruned_utreexo/consensus.rs
Labels: bug, CI

#461 Improve the PR template checklist
  .github/PULL_REQUEST_TEMPLATE.md
  justfile
Labels: documentation, chore, CI

#436 utils.nix and more nix flake checks
  .github/workflows/nix.yml
  contrib/nix/build_floresta.nix
  contrib/nix/build_utreexod.nix
  contrib/nix/default.nix
  contrib/nix/nix_building_response_table.sh
  contrib/nix/utils.nix
  flake.lock
  flake.nix
Labels: code quality, functional tests, nix

#454 wire: Some small hardening and bugfixes on connection logic
  crates/floresta-wire/src/p2p_wire/address_man.rs
  crates/floresta-wire/src/p2p_wire/chain_selector.rs
  crates/floresta-wire/src/p2p_wire/node.rs
  crates/floresta-wire/src/p2p_wire/node_context.rs
  crates/floresta-wire/src/p2p_wire/running_node.rs
  crates/floresta-wire/src/p2p_wire/sync_node.rs
Labels: bug, code quality

#460 Added docs for proof_util module
  crates/floresta-chain/src/pruned_utreexo/udata.rs
Labels: documentation, code quality
