Repository vinteumorg/Floresta, pull requests merged in 2025-07, with the labels that each got.

#542 chore: update chain values for release
  crates/floresta-chain/src/pruned_utreexo/chainparams.rs
  crates/floresta-wire/src/p2p_wire/seeds/mainnet_seeds.json
Labels: chore, consensus

#537 Wire: small fixes and improvements
  crates/floresta-wire/src/p2p_wire/node.rs
  crates/floresta-wire/src/p2p_wire/node_context.rs
  crates/floresta-wire/src/p2p_wire/peer.rs
  crates/floresta-wire/src/p2p_wire/running_node.rs
  crates/floresta-wire/src/p2p_wire/sync_node.rs
  crates/floresta-wire/src/p2p_wire/transport.rs
  tests/floresta-cli/addnode-test.py
Labels: bug, code quality

#549 Add missing `checkTransaction` rules
  crates/floresta-chain/src/pruned_utreexo/consensus.rs
  crates/floresta-chain/src/pruned_utreexo/error.rs
  crates/floresta-cli/src/lib.rs
  crates/floresta-wire/src/p2p_wire/running_node.rs
  crates/floresta-wire/src/p2p_wire/sync_node.rs
Labels: enhancement, chore, consensus

#553 Benchmark checksums and chainstore creation
  crates/floresta-chain/benches/chain_state_bench.rs
  crates/floresta-chain/src/pruned_utreexo/flat_chain_store.rs
Labels: code quality, performance

#552 florestad: fix `--connect`
  crates/floresta-wire/src/p2p_wire/node.rs
  tests/florestad/connect-test.py
Labels: bug, functional tests

#556 cli: rename rescan to rescanblockchain
  crates/floresta-cli/README.md
  crates/floresta-cli/src/main.rs
  crates/floresta-cli/src/rpc.rs
Labels: bug, RPC

#557 floresta-chain: fix a test feature problem
  crates/floresta-electrum/Cargo.toml
  crates/floresta-electrum/src/electrum_protocol.rs
Labels: bug, functional tests

#555 Florestad: refactor setup wallet data
  florestad/src/florestad.rs
Labels: chore, code quality

#559 wire: don't spam the logs with `PeerNotFound`
  crates/floresta-wire/src/p2p_wire/address_man.rs
  crates/floresta-wire/src/p2p_wire/running_node.rs
Labels: bug

#521 Add template to RPC commands documentation
  .gitignore
  CONTRIBUTING.md
  Dockerfile
  contrib/dist/gen_manpages.sh
  crates/floresta-cli/README.md
  crates/floresta-cli/src/main.rs
  crates/floresta-cli/src/rpc.rs
  doc/rpc/addnode.md
  doc/rpc/template.md
  doc/rpc_man/README.md
  flake.nix
  justfile
Labels: documentation, RPC

#562 fix: re-index didn't apply changes to chainstate
  crates/floresta-chain/src/pruned_utreexo/chain_state.rs
Labels: bug, consensus

#563 Man page cli rendering fix on template.md
  doc/rpc/template.md
Labels: documentation

#571 bump version for release
  Cargo.lock
  crates/floresta-chain/Cargo.toml
  crates/floresta-cli/Cargo.toml
  crates/floresta-common/Cargo.toml
  crates/floresta-compact-filters/Cargo.toml
  crates/floresta-electrum/Cargo.toml
  crates/floresta-watch-only/Cargo.toml
  crates/floresta-wire/Cargo.toml
  crates/floresta/Cargo.toml
  florestad/Cargo.toml
  fuzz/Cargo.toml
  metrics/Cargo.toml
  tests/example/electrum-test.py
Labels: chore

#568 CI: Check cargo doc lints
  .github/workflows/rust.yml
  crates/floresta-chain/src/pruned_utreexo/chain_state.rs
  crates/floresta-chain/src/pruned_utreexo/flat_chain_store.rs
  crates/floresta-chain/src/pruned_utreexo/mod.rs
  crates/floresta-watch-only/src/memory_database.rs
  crates/floresta-wire/src/p2p_wire/node.rs
  doc/rpc/addnode.md
  doc/rpc/template.md
  florestad/src/error.rs
  florestad/src/json_rpc/blockchain.rs
  justfile
Labels: code quality, CI

#526 test: added multithreading on functional tests
  .github/workflows/functional.yml
  doc/nix.md
  doc/running-tests.md
  flake.nix
  tests/example/bitcoin-test.py
  tests/example/electrum-test.py
  tests/example/functional-test.py
  tests/example/integration-test.py
  tests/example/utreexod-test.py
  tests/floresta-cli/addnode-test.py
  tests/floresta-cli/addnode-v1-test.py
  tests/floresta-cli/addnode-v2-test.py
  tests/floresta-cli/getblock-test.py
  tests/floresta-cli/getblockchaininfo-test.py
  tests/floresta-cli/getblockhash-test.py
  tests/floresta-cli/getblockheader-test.py
  tests/floresta-cli/getmemoryinfo-test.py
  tests/floresta-cli/getpeerinfo-test.py
  tests/floresta-cli/getroots-test.py
  tests/floresta-cli/getrpcinfo-test.py
  tests/floresta-cli/ping-test.py
  tests/floresta-cli/stop-test.py
  tests/floresta-cli/uptime-test.py
  tests/florestad/connect-test.py
  tests/florestad/reorg-chain-test.py
  tests/florestad/reorg-chain.py
  tests/florestad/restart-test.py
  tests/florestad/tls-fail-test.py
  tests/florestad/tls-test.py
  tests/prepare.sh
  tests/run.sh
  tests/run_tests.py
  tests/test_framework/__init__.py
  tests/test_framework/daemon/base.py
  tests/test_framework/rpc/base.py
  tests/test_framework/rpc/bitcoin.py
  tests/test_framework/rpc/floresta.py
  tests/test_framework/rpc/utreexo.py
  tests/test_runner.py
Labels: functional tests

#575 Update running tests
  doc/running-tests.md
Labels: code quality, functional tests

#548 chore(test): remove `-test` suffix from test files
  tests/example/bitcoin.py
  tests/example/electrum.py
  tests/example/functional.py
  tests/example/integration.py
  tests/example/utreexod.py
  tests/floresta-cli/addnode-v1.py
  tests/floresta-cli/addnode-v2.py
  tests/floresta-cli/getbestblockhash.py
  tests/floresta-cli/getblock.py
  tests/floresta-cli/getblockchaininfo.py
  tests/floresta-cli/getblockhash.py
  tests/floresta-cli/getblockheader.py
  tests/floresta-cli/getmemoryinfo.py
  tests/floresta-cli/getpeerinfo.py
  tests/floresta-cli/getroots.py
  tests/floresta-cli/getrpcinfo.py
  tests/floresta-cli/ping.py
  tests/floresta-cli/stop.py
  tests/floresta-cli/uptime.py
  tests/florestad/connect.py
  tests/florestad/reorg-chain.py
  tests/florestad/restart.py
  tests/florestad/tls-fail.py
  tests/florestad/tls.py
  tests/test_framework/__init__.py
  tests/test_runner.py
Labels: functional tests

#587 test: add a `getblockcount` rpc test
  tests/floresta-cli/getblockcount.py
  tests/test_framework/rpc/bitcoin.py
  tests/test_framework/rpc/floresta.py
  tests/test_framework/rpc/utreexo.py
  tests/test_runner.py
Labels: code quality, functional tests
