Repository vinteumorg/Floresta, pull requests merged in 2025-06, with the labels that each got.

#494 feat: BIP-0094 "testnet4"
  crates/floresta-chain/src/pruned_utreexo/chain_state.rs
  crates/floresta-chain/src/pruned_utreexo/chainparams.rs
  crates/floresta-chain/src/pruned_utreexo/consensus.rs
  crates/floresta-chain/src/pruned_utreexo/error.rs
  crates/floresta-wire/src/p2p_wire/address_man.rs
  crates/floresta-wire/src/p2p_wire/node.rs
  crates/floresta-wire/src/p2p_wire/running_node.rs
  crates/floresta-wire/src/p2p_wire/seeds/testnet4_seeds.json
  crates/floresta-wire/src/p2p_wire/sync_node.rs
Labels: enhancement, consensus

#502 Change create_connection return type on `floresta-wire/src/p2p_wire/node.rs`
  crates/floresta-wire/src/p2p_wire/error.rs
  crates/floresta-wire/src/p2p_wire/node.rs
  crates/floresta-wire/src/p2p_wire/running_node.rs
  crates/floresta-wire/src/p2p_wire/sync_node.rs
Labels: chore, code quality

#510 Fix lint lifetime warnings and docstring tests
  crates/floresta-chain/src/pruned_utreexo/flat_chain_store.rs
  crates/floresta-common/src/macros.rs
  crates/floresta-watch-only/src/memory_database.rs
Labels: lint

#505 [RPC] Implementation detail for addnode: connect to peer after add it
  crates/floresta-wire/src/p2p_wire/node.rs
  crates/floresta-wire/src/p2p_wire/running_node.rs
  tests/floresta-cli/addnode-test.py
Labels: functional tests, RPC

#501 wire: prefer v2 connections for non-utreexo peers
  crates/floresta-cli/src/main.rs
  crates/floresta-cli/src/rpc.rs
  crates/floresta-wire/src/p2p_wire/node.rs
  crates/floresta-wire/src/p2p_wire/peer.rs
  florestad/src/cli.rs
  florestad/src/main.rs
  tests/floresta-cli/addnode-test.py
  tests/test_framework/rpc/bitcoin.py
Labels: enhancement

#512 Use `&mut self` in FlatChainStore inner methods
  crates/floresta-chain/src/pruned_utreexo/flat_chain_store.rs
Labels: code quality

#519 Use FlatChainStore in tests and benches
  .github/workflows/benchmarks.yml
  crates/floresta-chain/Cargo.toml
  crates/floresta-chain/benches/chain_state_bench.rs
  crates/floresta-chain/src/lib.rs
  crates/floresta-chain/src/pruned_utreexo/chain_state.rs
  crates/floresta-chain/src/pruned_utreexo/flat_chain_store.rs
  doc/benchmarking.md
  florestad/src/florestad.rs
  justfile
Labels: enhancement, code quality

#520 [RPC] Change the stop return value to be compliant wit Bitcoin Core
  crates/floresta-cli/src/lib.rs
  crates/floresta-cli/src/main.rs
  florestad/src/json_rpc/control.rs
  tests/floresta-cli/stop-test.py
Labels: bug, functional tests, RPC

#498 chain: handle accumulator reorg
  crates/floresta-chain/src/pruned_utreexo/chain_state.rs
  crates/floresta-chain/src/pruned_utreexo/chainstore.rs
  crates/floresta-chain/src/pruned_utreexo/error.rs
  crates/floresta-chain/src/pruned_utreexo/flat_chain_store.rs
  crates/floresta-chain/src/pruned_utreexo/mod.rs
  tests/florestad/reorg-chain.py
  tests/prepare.sh
  tests/test_framework/rpc/base.py
  tests/test_framework/rpc/utreexo.py
Labels: bug, consensus

#517 [RPC] Fix getrpcinfo to return the duration compliant with core
  crates/floresta-cli/src/main.rs
  florestad/src/json_rpc/control.rs
  tests/floresta-cli/addnode-test.py
  tests/floresta-cli/getrpcinfo-test.py
  tests/test_framework/__init__.py
  tests/test_framework/rpc/bitcoin.py
Labels: bug, RPC

#528 Remove the `cli_wire` module
  crates/floresta-wire/src/cli_wire/mod.rs
Labels: chore, code quality

#531 Log RPC server info
  florestad/src/florestad.rs
  florestad/src/json_rpc/server.rs
Labels: documentation, enhancement

#533 remove core2
  Cargo.lock
  crates/floresta-common/Cargo.toml
Labels: dependencies, code quality

#532 Simplify flat store, create `get_header_by_height`
  crates/floresta-chain/src/pruned_utreexo/chain_state.rs
  crates/floresta-chain/src/pruned_utreexo/chainstore.rs
  crates/floresta-chain/src/pruned_utreexo/flat_chain_store.rs
  crates/floresta-chain/src/pruned_utreexo/mod.rs
Labels: enhancement, code quality, performance

#534 Fix action ip:port address for log RPC info
  florestad/src/json_rpc/server.rs
Labels: code quality

#527 florestad: make FlatChainstore the default
  .github/workflows/benchmarks.yml
  contrib/feature_matrix.sh
  crates/floresta-chain/Cargo.toml
  crates/floresta-chain/benches/chain_state_bench.rs
  crates/floresta-chain/src/lib.rs
  crates/floresta-chain/src/pruned_utreexo/chain_state.rs
  crates/floresta-chain/src/pruned_utreexo/chainstore.rs
  crates/floresta-chain/src/pruned_utreexo/error.rs
  crates/floresta-chain/src/pruned_utreexo/flat_chain_store.rs
  crates/floresta-chain/src/pruned_utreexo/kv_chainstore.rs
  crates/floresta-chain/src/pruned_utreexo/mod.rs
  crates/floresta-chain/src/pruned_utreexo/udata.rs
  crates/floresta-electrum/Cargo.toml
  crates/floresta-wire/Cargo.toml
  crates/floresta-wire/src/p2p_wire/node.rs
  crates/floresta-wire/src/p2p_wire/tests/sync_node.rs
  crates/floresta/Cargo.toml
  crates/floresta/examples/chainstate-builder.rs
  crates/floresta/examples/node.rs
  florestad/Cargo.toml
  florestad/src/florestad.rs
  justfile
  tests/floresta-cli/ping-test.py
Labels: enhancement, dependencies, chore

#530 Rename `florestad/src/json_rpc/res.rs::Error`
  florestad/src/json_rpc/blockchain.rs
  florestad/src/json_rpc/control.rs
  florestad/src/json_rpc/network.rs
  florestad/src/json_rpc/res.rs
  florestad/src/json_rpc/server.rs
Labels: code quality

#541 Lint `fuzz` and `metrics`
  .github/workflows/fuzz.yml
  Cargo.toml
  contrib/feature_matrix.sh
  doc/benchmarking.md
  justfile
  metrics/Cargo.toml
Labels: lint, fuzz
