Repository vinteumorg/Floresta, pull requests merged in 2025-08, with the labels that each got.

#593 Remove `assume_valid_index` from `BestChain`
  Cargo.lock
  crates/floresta-chain/Cargo.toml
  crates/floresta-chain/src/pruned_utreexo/chain_state.rs
  crates/floresta-chain/src/pruned_utreexo/chainstore.rs
  crates/floresta-chain/src/pruned_utreexo/flat_chain_store.rs
  crates/floresta-chain/testdata/v0_flat_metadata.bin
Labels: chore, code quality, consensus

#599 Fix reindex during chain selection
  crates/floresta-chain/src/pruned_utreexo/chain_state.rs
  crates/floresta-wire/src/p2p_wire/chain_selector.rs
  florestad/src/florestad.rs
Labels: bug, chore

#602 chore(ci): add spell-check
  .github/workflows/rust.yml
  CONTRIBUTING.md
  contrib/install.sh
  contrib/nix/build_floresta.nix
  crates/floresta-chain/src/pruned_utreexo/chain_state.rs
  crates/floresta-chain/src/pruned_utreexo/flat_chain_store.rs
  crates/floresta-chain/src/pruned_utreexo/partial_chain.rs
  crates/floresta-cli/src/parsers.rs
  crates/floresta-cli/src/rpc_types.rs
  crates/floresta-common/src/spsc.rs
  crates/floresta-wire/src/p2p_wire/address_man.rs
  crates/floresta-wire/src/p2p_wire/chain_selector.rs
  crates/floresta-wire/src/p2p_wire/mempool.rs
  crates/floresta-wire/src/p2p_wire/node_interface.rs
  crates/floresta-wire/src/p2p_wire/running_node.rs
  doc/nix.md
  doc/run.md
  florestad/src/florestad.rs
  florestad/src/json_rpc/server.rs
  justfile
  tests/floresta-cli/getblockcount.py
  tests/floresta-cli/getmemoryinfo.py
  tests/test_framework/__init__.py
  tests/test_framework/bitcoin.py
  tests/test_framework/daemon/base.py
  tests/test_framework/rpc/base.py
  tests/test_framework/rpc/floresta.py
  typos.toml
Labels: documentation, chore, code quality

#604 Merge Description and Notes, and adds new how-to-test in place
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#596 feat(chain): Enable subscriptions to blocks with input UTXOs
  crates/floresta-chain/src/lib.rs
  crates/floresta-chain/src/pruned_utreexo/chain_state.rs
  crates/floresta-chain/src/pruned_utreexo/mod.rs
  crates/floresta-watch-only/src/lib.rs
  crates/floresta/examples/indexer.rs
  crates/floresta/examples/node.rs
  florestad/src/zmq.rs
Labels: enhancement

#615 [Fix] Lock lib dns-lookup version to 2.0.4
  florestad/Cargo.toml
Labels: bug, dependencies

#579 refactor: remove `expect`, add error handling and lints for `florestad`
  Cargo.lock
  florestad/Cargo.toml
  florestad/src/config_file.rs
  florestad/src/error.rs
  florestad/src/florestad.rs
  florestad/src/main.rs
  florestad/src/wallet_input.rs
Labels: chore, code quality, lint
