Repository vinteumorg/Floresta, pull requests merged in 2025-09, with the labels that each got.

#584 RPC: don't use the [] syntax, as it will panic
  florestad/src/json_rpc/mod.rs
  florestad/src/json_rpc/request.rs
  florestad/src/json_rpc/res.rs
  florestad/src/json_rpc/server.rs
Labels: bug, chore, code quality, RPC

#610 [FIX] Instantiate path with cargo bin path to find the binary
  justfile
Labels: lint

#634 fix(rpc): add default `Testnet4` RPC port to server and client
  bin/floresta-cli/src/main.rs
  crates/floresta-node/src/florestad.rs
  crates/floresta-node/src/json_rpc/res.rs
  crates/floresta-node/src/json_rpc/server.rs
  crates/floresta-wire/src/p2p_wire/address_man.rs
  crates/floresta-wire/src/p2p_wire/node.rs
Labels: bug, chore

#630 doc: add some documentation for docker setup
  doc/README.md
  doc/docker.md
Labels: documentation
